apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/instance: fluxversions
    app.kubernetes.io/name: fluxversions
    app.kubernetes.io/version: v0.1.0
  name: fluxversions
  namespace: fluxversions
spec:
  schedule: '@daily'
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/instance: fluxversions
        app.kubernetes.io/name: fluxversions
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/instance: fluxversions
            app.kubernetes.io/name: fluxversions
        spec:
          containers:
          - name: fluxversions
            image: jonkerj/fluxversions:v0.1.0
            resources:
              limits: {cpu: 0.25, memory: 256Mi}
              requests: {cpu: 0.25, memory: 32Mi}
          serviceAccountName: fluxversions
          restartPolicy: Never
